//Currency's types
export const CHANGE_CURRENCY = "CHANGE_CURRENCY";

//Cart's types
export const ADD_TO_CART = "ADD_TO_CART";
export const CHANGE_PRODUCTS_AMOUNT = "CHANGE_PRODUCTS_AMOUNT";
export const CHANGE_PRODUCTS_ATTRIBUTE = "CHANGE_PRODUCTS_ATTRIBUTE";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
