//Currency's types
export const CHANGE_CURRENCY = "CHANGE_CURRENCY";

//Cart's types
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const CHANGE_PRODUCTS_AMOUNT = "CHANGE_PRODUCTS_AMOUNT";
export const CHANGE_PRODUCTS_ATTRIBUTE = "CHANGE_PRODUCTS_ATTRIBUTE";
export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART";

//MiniCart
export const TOGGLE_MINI_CART = "TOGGLE_MINI_CART";
export const HIDE_MINI_CART = "HIDE_MINI_CART";
